const backendDomain=process.env.REACT_APP_BACKEND_URL
const SummaryApi={
    signup:{
        url:`${backendDomain}/api/signup`,
        method:"post"
    },
    signin:{
        url:`${backendDomain}/api/signin`,
        method:"post"
    },
    current_user:{
        url:`${backendDomain}/api/user-details`,
        method:"get",
    },
    logout_user:{
        url:`${backendDomain}/api/userLogout`,
        method:"get",
    },
    allUser:{
        url:`${backendDomain}/api/all-users`,
        method:"get",
    },
    updateUser:{
        url:`${backendDomain}/api/update-user`,
        method:"post",
    },
    uploadProduct:{
        url:`${backendDomain}/api/upload-product`,
        method:"post",
    },
    allProduct:{
        url:`${backendDomain}/api/get-product`,
        method:"get",
    },
    updateProduct:{
        url:`${backendDomain}/api/update-product`,
        method:"post",
    },
    categoryProduct:{
        url:`${backendDomain}/api/get-categoryProduct`,
        method:"get",
    },
    categoryWiseProduct:{
        url:`${backendDomain}/api/category-product`,
        method:"post",
    },
    productDetails:{
        url:`${backendDomain}/api/product-details`,
        method:"post",
    },
    addToCardProduct:{
        url:`${backendDomain}/api/addtocart`,
        method:"post",
    },
    addToCardProductCount:{
        url:`${backendDomain}/api/countAddToCardProduct`,
        method:"get",
    },
    addToCardProductView:{
        url:`${backendDomain}/api/view-card-product`,
        method:"get",
    },
    updateCartProduct:{
        url:`${backendDomain}/api/update-card-product`,
        method:"post",
    },
    deleteCartProduct:{
        url:`${backendDomain}/api/delete-card-product`,
        method:"post",
    },
    searchProduct:{
        url:`${backendDomain}/api/search`,
        method:"get",
    },
    filterProduct:{
        url:`${backendDomain}/api/filter-product`,
        method:"post", 
    }
    
}
export default SummaryApi
